### 사진 보내기
POST localhost:3000/upload
Content-Type: multipart/form-data; boundary=----hi

------hi
Content-Disposition: form-data; name="image"; filename="hello.png"
Content-Type: text/event-stream

/Users/moon/Desktop/hello.png
------hi--


###
GET www.naver.com


