
###
POST http://localhost:8000/api/users
Accept: application/json
Content-Type: application/json

{
  "userName": "Dongmin",
  "address": "Dajeon-si Yuseong-gu",
  "email": "water8760@naver.com",
  "phoneNumber": "01012341234"

}

###
GET http://localhost:8000/api/users/userName/Dongmin
Accept: application/json

###
GET http://localhost:8000/api/users/address/Dajeon-si
Accept: application/json

###
GET http://localhost:8000/api/users/email/water8760@naver.com
Accept: application/json

###
PATCH http://localhost:8000/api/users/6416d4f436ca46e0260893b1
Accept: application/json
Content-Type: application/json

{
  "address": "DaeJeon"
}

###
DELETE http://localhost:8000/api/users/64202f38fcf147193de865e3

###
GET http://localhost:8000/api/users/jwt/6416d4f436ca46e0260893b1
Accept: application/json
Content-Type: application/json