###
POST http://localhost:8000/api/users
Accept: application/json
Content-Type: application/json

{
  "name": "Dongmin",
  "email": "water_8760@naver.com",
  "address": "Daejeon Yuseong Dukmeong"
}

###
POST http://localhost:8000/api/users
Accept: application/json
Content-Type: application/json

{
  "name": "JaeYong",
  "email": "1234@naver.com",
  "address": "Daejeon Yuseong Hackha"
}

###
DELETE http://localhost:8000/api/users/640d7f03a5cc26c6397acbe4
Accept: application/json

###
PATCH http://localhost:8000/api/users/640d7f03a5cc26c6397acbe4
Accept: application/json
Content-Type: application/json

{
  "email": "wisoft@naver.com",
  "name": "Dongmin"
}
