###
POST http://localhost:8000/api/users
Accept: application/json
Content-Type: application/json

{
  "name": "Dongmin",
  "email": "water_8760@naver.com",
  "address": "Daejeon Yuseong Dukmeong"
}

###
POST http://localhost:8000/api/users
Accept: application/json
Content-Type: application/json

{
  "name": "JaeYong",
  "email": "1234@naver.com",
  "address": "Daejeon Yuseong Hackha"
}

###
DELETE http://localhost:8000/api/users/640d897487a420218e1f4371
Accept: application/json

###
PATCH http://localhost:8000/api/users/640d8e13bcfbd268b74f91e5
Accept: application/json
Content-Type: application/json

{
  "name": "Dongmin",
  "email": "wisoft@naver.com"

}
